import type { DashboardPageKey } from "@/lib/dashboard-pages";

export type DashboardFeatureCategoryKey =
  | "business"
  | "booking"
  | "coaching"
  | "retention"
  | "billing"
  | "mobile"
  | "marketing"
  | "integrations";

export interface DashboardFeatureDefinition {
  readonly key: string;
  readonly title: string;
  readonly categoryKey: DashboardFeatureCategoryKey;
  readonly categoryTitle: string;
  readonly dashboardPage: DashboardPageKey;
  readonly defaultValue: boolean;
  readonly description: string;
  readonly statusLabel: "Live" | "Expanded" | "New";
  readonly badgeLabel?: "NEW";
}

export const DASHBOARD_FEATURE_CATALOG: ReadonlyArray<DashboardFeatureDefinition> = [
  {
    key: "membership.management",
    title: "Membership Management",
    categoryKey: "business",
    categoryTitle: "Manage Your Business",
    dashboardPage: "members",
    defaultValue: true,
    description: "Manage members, memberships, waivers, and member portal access.",
    statusLabel: "Live",
  },
  {
    key: "staff.management",
    title: "Staff Management",
    categoryKey: "business",
    categoryTitle: "Manage Your Business",
    dashboardPage: "settings",
    defaultValue: true,
    description: "Invite owners, managers, trainers, and frontdesk team members per gym.",
    statusLabel: "Live",
  },
  {
    key: "access.24_7",
    title: "24/7 Gym Access System",
    categoryKey: "business",
    categoryTitle: "Manage Your Business",
    dashboardPage: "access",
    defaultValue: true,
    description: "Control remote access, owner unlock actions, and smart lock policies.",
    statusLabel: "Live",
  },
  {
    key: "checkin.studio",
    title: "Studio Check-in Software",
    categoryKey: "business",
    categoryTitle: "Manage Your Business",
    dashboardPage: "classes",
    defaultValue: true,
    description: "Handle frontdesk and QR check-ins tied directly to class attendance.",
    statusLabel: "Live",
  },
  {
    key: "analytics.advanced",
    title: "Advanced Analytics",
    categoryKey: "business",
    categoryTitle: "Manage Your Business",
    dashboardPage: "overview",
    defaultValue: true,
    description: "Track occupancy, revenue readiness, member health, and operational signals.",
    statusLabel: "Expanded",
  },
  {
    key: "clubs.multi_location",
    title: "Multi-Club Management",
    categoryKey: "business",
    categoryTitle: "Manage Your Business",
    dashboardPage: "settings",
    defaultValue: true,
    description: "Run multiple gyms from one tenant-aware platform with location-specific context.",
    statusLabel: "Live",
  },
  {
    key: "commerce.webshop_pos",
    title: "Webshop & PoS",
    categoryKey: "business",
    categoryTitle: "Manage Your Business",
    dashboardPage: "payments",
    defaultValue: false,
    description: "Enable on-site sales, product bundles, and simple retail checkout workflows.",
    statusLabel: "Expanded",
  },
  {
    key: "booking.scheduling",
    title: "Scheduling Software",
    categoryKey: "booking",
    categoryTitle: "Booking Options",
    dashboardPage: "classes",
    defaultValue: true,
    description: "Plan recurring sessions, capacity, trainers, and class focus in one flow.",
    statusLabel: "Live",
  },
  {
    key: "booking.group_classes",
    title: "Group Class Booking",
    categoryKey: "booking",
    categoryTitle: "Booking Options",
    dashboardPage: "classes",
    defaultValue: true,
    description: "Members can reserve live classes with waitlist support and attendance actions.",
    statusLabel: "Live",
  },
  {
    key: "booking.one_to_one",
    title: "1-1 Appointment Booking",
    categoryKey: "booking",
    categoryTitle: "Booking Options",
    dashboardPage: "classes",
    defaultValue: false,
    description: "Offer private PT or intro sessions with dedicated one-on-one booking slots.",
    statusLabel: "Expanded",
  },
  {
    key: "booking.online_trial",
    title: "Online Trial Booking",
    categoryKey: "booking",
    categoryTitle: "Booking Options",
    dashboardPage: "classes",
    defaultValue: true,
    description: "Expose public trial booking moments from the same scheduling layer.",
    statusLabel: "Expanded",
  },
  {
    key: "booking.credit_system",
    title: "Credit System",
    categoryKey: "booking",
    categoryTitle: "Booking Options",
    dashboardPage: "contracts",
    defaultValue: false,
    description: "Attach class packs and booking credits to memberships and one-off products.",
    statusLabel: "Expanded",
  },
  {
    key: "coaching.workout_plans",
    title: "Workout Plan Creator",
    categoryKey: "coaching",
    categoryTitle: "Coach Your Clients",
    dashboardPage: "coaching",
    defaultValue: false,
    description: "Build structured programming blocks, templates, and progressions for members.",
    statusLabel: "Expanded",
  },
  {
    key: "coaching.nutrition",
    title: "Nutrition Coaching",
    categoryKey: "coaching",
    categoryTitle: "Coach Your Clients",
    dashboardPage: "coaching",
    defaultValue: false,
    description: "Share nutrition guidance, check-ins, and goal-oriented support from the same workspace.",
    statusLabel: "Expanded",
  },
  {
    key: "coaching.on_demand_videos",
    title: "On Demand Videos",
    categoryKey: "coaching",
    categoryTitle: "Coach Your Clients",
    dashboardPage: "coaching",
    defaultValue: false,
    description: "Offer premium video libraries and member-only drill content outside live sessions.",
    statusLabel: "Expanded",
  },
  {
    key: "coaching.progress_tracking",
    title: "Progress Tracking",
    categoryKey: "coaching",
    categoryTitle: "Coach Your Clients",
    dashboardPage: "coaching",
    defaultValue: false,
    description: "Track milestones, adherence, coaching notes, and before/after progress updates.",
    statusLabel: "Expanded",
  },
  {
    key: "coaching.heart_rate",
    title: "Heart Rate Coaching",
    categoryKey: "coaching",
    categoryTitle: "Coach Your Clients",
    dashboardPage: "coaching",
    defaultValue: false,
    description: "Bring wearables and zone-based coaching signals into training workflows.",
    statusLabel: "Expanded",
  },
  {
    key: "coaching.ai_max",
    title: "MAX AI Coach",
    categoryKey: "coaching",
    categoryTitle: "Coach Your Clients",
    dashboardPage: "coaching",
    defaultValue: false,
    description: "Launch AI-assisted plan suggestions, prompts, and progress summaries for coaches.",
    statusLabel: "New",
    badgeLabel: "NEW",
  },
  {
    key: "retention.planner",
    title: "Retention Planner",
    categoryKey: "retention",
    categoryTitle: "Retain Your Customers",
    dashboardPage: "retention",
    defaultValue: false,
    description: "Monitor churn signals and trigger owner follow-up before members drop off.",
    statusLabel: "Expanded",
  },
  {
    key: "retention.community_groups",
    title: "Community & Groups",
    categoryKey: "retention",
    categoryTitle: "Retain Your Customers",
    dashboardPage: "retention",
    defaultValue: false,
    description: "Create club communities, group experiences, and accountability circles.",
    statusLabel: "Expanded",
  },
  {
    key: "retention.challenges_rewards",
    title: "Challenges & Rewards",
    categoryKey: "retention",
    categoryTitle: "Retain Your Customers",
    dashboardPage: "retention",
    defaultValue: false,
    description: "Run seasonal challenges, streak programs, and reward loops to keep members engaged.",
    statusLabel: "Expanded",
  },
  {
    key: "retention.questionnaire",
    title: "Questionnaire",
    categoryKey: "retention",
    categoryTitle: "Retain Your Customers",
    dashboardPage: "retention",
    defaultValue: false,
    description: "Collect feedback, readiness, and member intent with configurable questionnaires.",
    statusLabel: "Expanded",
  },
  {
    key: "retention.pro_content",
    title: "PRO+ Content",
    categoryKey: "retention",
    categoryTitle: "Retain Your Customers",
    dashboardPage: "retention",
    defaultValue: false,
    description: "Publish premium educational content and structured value-add journeys for paying members.",
    statusLabel: "Expanded",
  },
  {
    key: "retention.fitzone",
    title: "FitZone",
    categoryKey: "retention",
    categoryTitle: "Retain Your Customers",
    dashboardPage: "retention",
    defaultValue: false,
    description: "Run branded member experiences around habits, recovery, and lifestyle touchpoints.",
    statusLabel: "Expanded",
  },
  {
    key: "billing.processing",
    title: "Payment Processing",
    categoryKey: "billing",
    categoryTitle: "Billing Your Clients",
    dashboardPage: "payments",
    defaultValue: true,
    description: "Configure payment providers and operational settlement details per gym.",
    statusLabel: "Live",
  },
  {
    key: "billing.credit_cards",
    title: "Credit Card Payments",
    categoryKey: "billing",
    categoryTitle: "Billing Your Clients",
    dashboardPage: "payments",
    defaultValue: true,
    description: "Support one-time card payments and online checkout flows through Mollie.",
    statusLabel: "Live",
  },
  {
    key: "billing.direct_debit",
    title: "Direct Debit Processing",
    categoryKey: "billing",
    categoryTitle: "Billing Your Clients",
    dashboardPage: "payments",
    defaultValue: true,
    description: "Run recurring SEPA collection for memberships and contract renewals.",
    statusLabel: "Live",
  },
  {
    key: "billing.autocollect",
    title: "AutoCollect",
    categoryKey: "billing",
    categoryTitle: "Billing Your Clients",
    dashboardPage: "payments",
    defaultValue: false,
    description: "Automate payment follow-up, retries, and owner-side collection queues.",
    statusLabel: "New",
    badgeLabel: "NEW",
  },
  {
    key: "mobile.white_label",
    title: "White Label App",
    categoryKey: "mobile",
    categoryTitle: "Your Mobile App",
    dashboardPage: "mobile",
    defaultValue: false,
    description: "Expose the gym brand inside a configurable mobile shell for members.",
    statusLabel: "Expanded",
  },
  {
    key: "mobile.fitness_coaching",
    title: "Fitness Coaching App",
    categoryKey: "mobile",
    categoryTitle: "Your Mobile App",
    dashboardPage: "mobile",
    defaultValue: false,
    description: "Deliver coaching actions, schedules, and member journeys through the mobile app.",
    statusLabel: "Expanded",
  },
  {
    key: "mobile.nutrition_coaching",
    title: "Nutrition Coaching App",
    categoryKey: "mobile",
    categoryTitle: "Your Mobile App",
    dashboardPage: "mobile",
    defaultValue: false,
    description: "Bring nutrition guidance and accountability check-ins into the member app experience.",
    statusLabel: "Expanded",
  },
  {
    key: "mobile.checkin",
    title: "Mobile Check-in",
    categoryKey: "mobile",
    categoryTitle: "Your Mobile App",
    dashboardPage: "mobile",
    defaultValue: true,
    description: "Let members use mobile identity and QR flows for arrivals and studio access.",
    statusLabel: "Expanded",
  },
  {
    key: "marketing.email",
    title: "Email Marketing",
    categoryKey: "marketing",
    categoryTitle: "Marketing Tools",
    dashboardPage: "marketing",
    defaultValue: false,
    description: "Send targeted nurture and win-back campaigns from the same gym data model.",
    statusLabel: "Expanded",
  },
  {
    key: "marketing.promotions",
    title: "In-app Promotions",
    categoryKey: "marketing",
    categoryTitle: "Marketing Tools",
    dashboardPage: "marketing",
    defaultValue: false,
    description: "Launch app banners, upsells, and conversion moments tied to live member context.",
    statusLabel: "Expanded",
  },
  {
    key: "marketing.leads",
    title: "Lead Management",
    categoryKey: "marketing",
    categoryTitle: "Marketing Tools",
    dashboardPage: "marketing",
    defaultValue: false,
    description: "Track inbound leads, follow-up stages, and conversion from trial to contract.",
    statusLabel: "Expanded",
  },
  {
    key: "integrations.hardware",
    title: "Supported Hardware",
    categoryKey: "integrations",
    categoryTitle: "Integrations",
    dashboardPage: "integrations",
    defaultValue: true,
    description: "Manage smart locks, scanners, and connected club hardware from one view.",
    statusLabel: "Live",
  },
  {
    key: "integrations.software",
    title: "Software Integrations",
    categoryKey: "integrations",
    categoryTitle: "Integrations",
    dashboardPage: "integrations",
    defaultValue: false,
    description: "Connect CRMs, messaging, BI, and external business systems to the gym platform.",
    statusLabel: "Expanded",
  },
  {
    key: "integrations.equipment",
    title: "Equipment Integrations",
    categoryKey: "integrations",
    categoryTitle: "Integrations",
    dashboardPage: "integrations",
    defaultValue: false,
    description: "Pull workout and attendance context from connected training equipment.",
    statusLabel: "Expanded",
  },
  {
    key: "integrations.virtuagym_connect",
    title: "Virtuagym Connect",
    categoryKey: "integrations",
    categoryTitle: "Integrations",
    dashboardPage: "integrations",
    defaultValue: false,
    description: "Bridge roster, members, and migration data from Virtuagym-style installations.",
    statusLabel: "New",
    badgeLabel: "NEW",
  },
  {
    key: "integrations.body_composition",
    title: "Body Composition",
    categoryKey: "integrations",
    categoryTitle: "Integrations",
    dashboardPage: "integrations",
    defaultValue: false,
    description: "Attach body composition measurements and scan hardware to member progress records.",
    statusLabel: "Expanded",
  },
] as const;

export function getDashboardFeaturesForPage(page: DashboardPageKey) {
  return DASHBOARD_FEATURE_CATALOG.filter((feature) => feature.dashboardPage === page);
}
