import type { DashboardPageKey } from "@/lib/dashboard-pages";

export type DashboardFeatureCategoryKey =
  | "business"
  | "booking"
  | "coaching"
  | "retention"
  | "billing"
  | "mobile"
  | "marketing"
  | "integrations";

export interface DashboardFeatureDefinition {
  readonly key: string;
  readonly title: string;
  readonly categoryKey: DashboardFeatureCategoryKey;
  readonly categoryTitle: string;
  readonly dashboardPage: DashboardPageKey;
  readonly defaultValue: boolean;
  readonly description: string;
  readonly statusLabel: "Live" | "Expanded" | "New";
  readonly badgeLabel?: "NEW";
}

export const DASHBOARD_FEATURE_CATALOG: ReadonlyArray<DashboardFeatureDefinition> = [
  {
    key: "membership.management",
    title: "Leden en lidmaatschappen",
    categoryKey: "business",
    categoryTitle: "Bedrijf beheren",
    dashboardPage: "members",
    defaultValue: true,
    description: "Beheer leden, lidmaatschappen, waivers en toegang tot het ledenportaal.",
    statusLabel: "Live",
  },
  {
    key: "staff.management",
    title: "Medewerkers",
    categoryKey: "business",
    categoryTitle: "Bedrijf beheren",
    dashboardPage: "settings",
    defaultValue: true,
    description: "Nodig eigenaren, managers, trainers en baliemedewerkers uit per gym.",
    statusLabel: "Live",
  },
  {
    key: "access.24_7",
    title: "24/7 toegang",
    categoryKey: "business",
    categoryTitle: "Bedrijf beheren",
    dashboardPage: "access",
    defaultValue: true,
    description: "Beheer toegang op afstand, eigenaarsacties en beleid voor slimme sloten.",
    statusLabel: "Live",
  },
  {
    key: "checkin.studio",
    title: "Studio-aanwezigheid",
    categoryKey: "business",
    categoryTitle: "Bedrijf beheren",
    dashboardPage: "classes",
    defaultValue: true,
    description: "Registreer balie- en QR-aanwezigheid direct op lessen.",
    statusLabel: "Live",
  },
  {
    key: "analytics.advanced",
    title: "Geavanceerde analytics",
    categoryKey: "business",
    categoryTitle: "Bedrijf beheren",
    dashboardPage: "overview",
    defaultValue: true,
    description: "Volg bezetting, omzetgereedheid, ledensignalen en operationele aandachtspunten.",
    statusLabel: "Expanded",
  },
  {
    key: "clubs.multi_location",
    title: "Meerdere vestigingen",
    categoryKey: "business",
    categoryTitle: "Bedrijf beheren",
    dashboardPage: "settings",
    defaultValue: true,
    description: "Beheer meerdere gyms vanuit één platform met context per vestiging.",
    statusLabel: "Live",
  },
  {
    key: "commerce.webshop_pos",
    title: "Webshop en kassa",
    categoryKey: "business",
    categoryTitle: "Bedrijf beheren",
    dashboardPage: "payments",
    defaultValue: false,
    description: "Activeer verkoop per vestiging, productbundels en eenvoudige kassa-afrekening.",
    statusLabel: "Expanded",
  },
  {
    key: "booking.scheduling",
    title: "Roosterplanning",
    categoryKey: "booking",
    categoryTitle: "Reserveringen",
    dashboardPage: "classes",
    defaultValue: true,
    description: "Plan herhalende lessen, capaciteit, trainers en lesfocus vanuit één scherm.",
    statusLabel: "Live",
  },
  {
    key: "booking.group_classes",
    title: "Groepslessen boeken",
    categoryKey: "booking",
    categoryTitle: "Reserveringen",
    dashboardPage: "classes",
    defaultValue: true,
    description: "Laat leden lessen reserveren met wachtlijst en aanwezigheidsacties.",
    statusLabel: "Live",
  },
  {
    key: "booking.one_to_one",
    title: "1-op-1 afspraken",
    categoryKey: "booking",
    categoryTitle: "Reserveringen",
    dashboardPage: "classes",
    defaultValue: false,
    description: "Bied privé-PT of introductiesessies met eigen tijdsloten.",
    statusLabel: "Expanded",
  },
  {
    key: "booking.online_trial",
    title: "Online proefles boeken",
    categoryKey: "booking",
    categoryTitle: "Reserveringen",
    dashboardPage: "classes",
    defaultValue: true,
    description: "Publiceer proeflesmomenten vanuit dezelfde roosterlaag.",
    statusLabel: "Expanded",
  },
  {
    key: "booking.credit_system",
    title: "Strippenkaarten",
    categoryKey: "booking",
    categoryTitle: "Reserveringen",
    dashboardPage: "contracts",
    defaultValue: false,
    description: "Koppel strippenkaarten en ritten aan lidmaatschappen en losse producten.",
    statusLabel: "Expanded",
  },
  {
    key: "coaching.workout_plans",
    title: "Trainingsplannen",
    categoryKey: "coaching",
    categoryTitle: "Coaching",
    dashboardPage: "coaching",
    defaultValue: false,
    description: "Bouw programma's, templates en progressies voor leden.",
    statusLabel: "Expanded",
  },
  {
    key: "coaching.nutrition",
    title: "Voedingscoaching",
    categoryKey: "coaching",
    categoryTitle: "Coaching",
    dashboardPage: "coaching",
    defaultValue: false,
    description: "Deel voedingsbegeleiding, voortgangsmomenten en doelgerichte ondersteuning.",
    statusLabel: "Expanded",
  },
  {
    key: "coaching.on_demand_videos",
    title: "Videotheek op aanvraag",
    categoryKey: "coaching",
    categoryTitle: "Coaching",
    dashboardPage: "coaching",
    defaultValue: false,
    description: "Bied verdiepende videotheken en techniekcontent alleen voor leden aan.",
    statusLabel: "Expanded",
  },
  {
    key: "coaching.progress_tracking",
    title: "Voortgang bijhouden",
    categoryKey: "coaching",
    categoryTitle: "Coaching",
    dashboardPage: "coaching",
    defaultValue: false,
    description: "Volg mijlpalen, coachingnotities en voortgangsupdates.",
    statusLabel: "Expanded",
  },
  {
    key: "coaching.heart_rate",
    title: "Hartslagcoaching",
    categoryKey: "coaching",
    categoryTitle: "Coaching",
    dashboardPage: "coaching",
    defaultValue: false,
    description: "Gebruik sporthorloges en zonesignalen in trainingsbegeleiding.",
    statusLabel: "Expanded",
  },
  {
    key: "coaching.ai_max",
    title: "MAX AI Coach",
    categoryKey: "coaching",
    categoryTitle: "Coaching",
    dashboardPage: "coaching",
    defaultValue: false,
    description: "Gebruik AI-ondersteuning voor plansuggesties en voortgangssamenvattingen.",
    statusLabel: "New",
    badgeLabel: "NEW",
  },
  {
    key: "retention.planner",
    title: "Retentieplanner",
    categoryKey: "retention",
    categoryTitle: "Retentie",
    dashboardPage: "retention",
    defaultValue: false,
    description: "Volg opzegsignalen en start opvolging voordat leden afhaken.",
    statusLabel: "Expanded",
  },
  {
    key: "retention.community_groups",
    title: "Clubgroepen",
    categoryKey: "retention",
    categoryTitle: "Retentie",
    dashboardPage: "retention",
    defaultValue: false,
    description: "Maak clubgroepen en vaste verantwoordingskringen aan.",
    statusLabel: "Expanded",
  },
  {
    key: "retention.challenges_rewards",
    title: "Uitdagingen en beloningen",
    categoryKey: "retention",
    categoryTitle: "Retentie",
    dashboardPage: "retention",
    defaultValue: false,
    description: "Organiseer uitdagingen, reeksen en beloningen om leden betrokken te houden.",
    statusLabel: "Expanded",
  },
  {
    key: "retention.questionnaire",
    title: "Vragenlijsten",
    categoryKey: "retention",
    categoryTitle: "Retentie",
    dashboardPage: "retention",
    defaultValue: false,
    description: "Verzamel feedback, paraatheid en intentie met configureerbare vragenlijsten.",
    statusLabel: "Expanded",
  },
  {
    key: "retention.pro_content",
    title: "PRO+ ledencontent",
    categoryKey: "retention",
    categoryTitle: "Retentie",
    dashboardPage: "retention",
    defaultValue: false,
    description: "Publiceer verdiepende educatie en gestructureerde ledentrajecten.",
    statusLabel: "Expanded",
  },
  {
    key: "retention.fitzone",
    title: "FitZone",
    categoryKey: "retention",
    categoryTitle: "Retentie",
    dashboardPage: "retention",
    defaultValue: false,
    description: "Bouw merkervaringen rond gewoontes, herstel en leefstijl.",
    statusLabel: "Expanded",
  },
  {
    key: "billing.processing",
    title: "Betaalverwerking",
    categoryKey: "billing",
    categoryTitle: "Betalingen",
    dashboardPage: "payments",
    defaultValue: true,
    description: "Configureer betaalproviders en uitbetalingsdetails per gym.",
    statusLabel: "Live",
  },
  {
    key: "billing.credit_cards",
    title: "Kaartbetalingen",
    categoryKey: "billing",
    categoryTitle: "Betalingen",
    dashboardPage: "payments",
    defaultValue: true,
    description: "Ondersteun eenmalige betaling met kaart en online checkout via Mollie.",
    statusLabel: "Live",
  },
  {
    key: "billing.direct_debit",
    title: "Incasso",
    categoryKey: "billing",
    categoryTitle: "Betalingen",
    dashboardPage: "payments",
    defaultValue: true,
    description: "Verwerk terugkerende SEPA-incasso voor lidmaatschappen en verlengingen.",
    statusLabel: "Live",
  },
  {
    key: "billing.autocollect",
    title: "AutoCollect",
    categoryKey: "billing",
    categoryTitle: "Betalingen",
    dashboardPage: "payments",
    defaultValue: false,
    description: "Automatiseer betaalopvolging, herinneringen en open betaalacties voor eigenaren.",
    statusLabel: "New",
    badgeLabel: "NEW",
  },
  {
    key: "mobile.white_label",
    title: "Merkapp",
    categoryKey: "mobile",
    categoryTitle: "Mobiele app",
    dashboardPage: "mobile",
    defaultValue: false,
    description: "Toon het gymmerk in een configureerbare mobiele app voor leden.",
    statusLabel: "Expanded",
  },
  {
    key: "mobile.fitness_coaching",
    title: "Fitnesscoaching-app",
    categoryKey: "mobile",
    categoryTitle: "Mobiele app",
    dashboardPage: "mobile",
    defaultValue: false,
    description: "Breng coachingacties, roosters en lidroutes samen in de mobiele app.",
    statusLabel: "Expanded",
  },
  {
    key: "mobile.nutrition_coaching",
    title: "Voedingscoaching-app",
    categoryKey: "mobile",
    categoryTitle: "Mobiele app",
    dashboardPage: "mobile",
    defaultValue: false,
    description: "Maak voeding, opvolging en voortgangsmomenten beschikbaar in de app.",
    statusLabel: "Expanded",
  },
  {
    key: "mobile.checkin",
    title: "Mobiele aankomst",
    categoryKey: "mobile",
    categoryTitle: "Mobiele app",
    dashboardPage: "mobile",
    defaultValue: true,
    description: "Laat leden mobiel of via QR aankomen bij lessen en studio's.",
    statusLabel: "Expanded",
  },
  {
    key: "marketing.email",
    title: "E-mailmarketing",
    categoryKey: "marketing",
    categoryTitle: "Marketing",
    dashboardPage: "marketing",
    defaultValue: false,
    description: "Stuur gerichte nurture- en winbackcampagnes vanuit gymdata.",
    statusLabel: "Expanded",
  },
  {
    key: "marketing.promotions",
    title: "In-app promoties",
    categoryKey: "marketing",
    categoryTitle: "Marketing",
    dashboardPage: "marketing",
    defaultValue: false,
    description: "Publiceer banners, upsells en conversiemomenten in de app.",
    statusLabel: "Expanded",
  },
  {
    key: "marketing.leads",
    title: "Aanvraagbeheer",
    categoryKey: "marketing",
    categoryTitle: "Marketing",
    dashboardPage: "marketing",
    defaultValue: false,
    description: "Volg aanvragen, opvolging en conversie van proefles naar lidmaatschap.",
    statusLabel: "Expanded",
  },
  {
    key: "integrations.hardware",
    title: "Ondersteunde hardware",
    categoryKey: "integrations",
    categoryTitle: "Integraties",
    dashboardPage: "integrations",
    defaultValue: true,
    description: "Beheer sloten, scanners en clubhardware vanuit één overzicht.",
    statusLabel: "Live",
  },
  {
    key: "integrations.software",
    title: "Softwarekoppelingen",
    categoryKey: "integrations",
    categoryTitle: "Integraties",
    dashboardPage: "integrations",
    defaultValue: false,
    description: "Koppel CRM, berichten, BI en externe bedrijfssoftware.",
    statusLabel: "Expanded",
  },
  {
    key: "integrations.equipment",
    title: "Apparaatkoppelingen",
    categoryKey: "integrations",
    categoryTitle: "Integraties",
    dashboardPage: "integrations",
    defaultValue: false,
    description: "Gebruik trainings- en aanwezigheidsdata uit verbonden apparatuur.",
    statusLabel: "Expanded",
  },
  {
    key: "integrations.virtuagym_connect",
    title: "Virtuagym Connect",
    categoryKey: "integrations",
    categoryTitle: "Integraties",
    dashboardPage: "integrations",
    defaultValue: false,
    description: "Verbind rooster-, leden- en migratiedata uit Virtuagym-achtige installaties.",
    statusLabel: "New",
    badgeLabel: "NEW",
  },
  {
    key: "integrations.body_composition",
    title: "Lichaamssamenstelling",
    categoryKey: "integrations",
    categoryTitle: "Integraties",
    dashboardPage: "integrations",
    defaultValue: false,
    description: "Koppel metingen en scanapparatuur aan ledenvoortgang.",
    statusLabel: "Expanded",
  },
] as const;

export function getDashboardFeaturesForPage(page: DashboardPageKey) {
  return DASHBOARD_FEATURE_CATALOG.filter((feature) => feature.dashboardPage === page);
}
